// Generated by scripts/generate-response-types.js from the checked-in protocol snapshot.
// Matches lib/proto-decode: uint64 strings, absent scalars/messages null, repeated fields arrays.
export interface CMsgConnectionStatus {
	status: number | null;
	client_session_need: number | null;
	queue_position: number | null;
	queue_size: number | null;
	wait_seconds: number | null;
	estimated_wait_seconds_remaining: number | null;
}
export interface CMsgGCCStrike15_v2_MatchmakingGC2ClientHello {
	account_id: number | null;
	ongoingmatch: CMsgGCCStrike15_v2_MatchmakingGC2ClientReserve | null;
	global_stats: GlobalStatistics | null;
	penalty_seconds: number | null;
	penalty_reason: number | null;
	vac_banned: number | null;
	ranking: PlayerRankingInfo | null;
	commendation: PlayerCommendationInfo | null;
	medals: PlayerMedalsInfo | null;
	my_current_event: TournamentEvent | null;
	my_current_event_teams: TournamentTeam[];
	my_current_team: TournamentTeam | null;
	my_current_event_stages: TournamentEvent[];
	survey_vote: number | null;
	activity: AccountActivity | null;
	player_level: number | null;
	player_cur_xp: number | null;
	player_xp_bonus_flags: number | null;
	rankings: PlayerRankingInfo[];
	owcaseid: string | null;
}
export interface CMsgGCCStrike15_v2_MatchmakingGC2ClientReserve {
	serverid: string | null;
	direct_udp_ip: number | null;
	direct_udp_port: number | null;
	reservationid: string | null;
	reservation: CMsgGCCStrike15_v2_MatchmakingGC2ServerReserve | null;
	map: string | null;
	server_address: string | null;
	gs_ping: DataCenterPing | null;
	gs_location_id: number | null;
}
export interface CMsgGCCStrike15_v2_MatchmakingGC2ServerReserve {
	account_ids: number[];
	game_type: number | null;
	match_id: string | null;
	server_version: number | null;
	flags: number | null;
	rankings: PlayerRankingInfo[];
	encryption_key: string | null;
	encryption_key_pub: string | null;
	party_ids: number[];
	whitelist: IpAddressMask[];
	tv_master_steamid: string | null;
	tournament_event: TournamentEvent | null;
	tournament_teams: TournamentTeam[];
	tournament_casters_account_ids: number[];
	tv_relay_steamid: string | null;
	pre_match_data: CPreMatchInfoData | null;
	tv_control: number | null;
	op_var_values: OperationalVarValue[];
	socache_control: number | null;
	teammate_colors: number[];
	match_id_additional: number | null;
	clan_tags: string[];
}
export interface PlayerRankingInfo {
	account_id: number | null;
	rank_id: number | null;
	wins: number | null;
	rank_change: number | null;
	rank_type_id: number | null;
	tv_control: number | null;
	rank_window_stats: string | null;
	leaderboard_name: string | null;
	rank_if_win: number | null;
	rank_if_lose: number | null;
	rank_if_tie: number | null;
	per_map_rank: PlayerRankingInfo_PerMapRank[];
	leaderboard_name_status: number | null;
	highest_rank: number | null;
	rank_expiry: number | null;
}
export interface PlayerRankingInfo_PerMapRank {
	map_id: number | null;
	rank_id: number | null;
	wins: number | null;
}
export interface IpAddressMask {
	a: number | null;
	b: number | null;
	c: number | null;
	d: number | null;
	bits: number | null;
	token: number | null;
}
export interface TournamentEvent {
	event_id: number | null;
	event_tag: string | null;
	event_name: string | null;
	event_time_start: number | null;
	event_time_end: number | null;
	event_public: number | null;
	event_stage_id: number | null;
	event_stage_name: string | null;
	active_section_id: number | null;
}
export interface TournamentTeam {
	team_id: number | null;
	team_tag: string | null;
	team_flag: string | null;
	team_name: string | null;
	players: TournamentPlayer[];
}
export interface TournamentPlayer {
	account_id: number | null;
	player_nick: string | null;
	player_name: string | null;
	player_dob: number | null;
	player_flag: string | null;
	player_location: string | null;
	player_desc: string | null;
}
export interface CPreMatchInfoData {
	predictions_pct: number | null;
	draft: CDataGCCStrike15_v2_TournamentMatchDraft | null;
	stats: CPreMatchInfoData_TeamStats[];
	wins: number[];
}
export interface CDataGCCStrike15_v2_TournamentMatchDraft {
	event_id: number | null;
	event_stage_id: number | null;
	team_id_0: number | null;
	team_id_1: number | null;
	maps_count: number | null;
	maps_current: number | null;
	team_id_start: number | null;
	team_id_veto1: number | null;
	team_id_pickn: number | null;
	drafts: CDataGCCStrike15_v2_TournamentMatchDraft_Entry[];
	vote_mapid_0: number[];
	vote_mapid_1: number[];
	vote_mapid_2: number[];
	vote_mapid_3: number[];
	vote_mapid_4: number[];
	vote_mapid_5: number[];
	vote_starting_side: number[];
	vote_phase: number | null;
	vote_phase_start: number | null;
	vote_phase_length: number | null;
}
export interface CDataGCCStrike15_v2_TournamentMatchDraft_Entry {
	mapid: number | null;
	team_id_ct: number | null;
}
export interface CPreMatchInfoData_TeamStats {
	match_info_idxtxt: number | null;
	match_info_txt: string | null;
	match_info_teams: string[];
}
export interface OperationalVarValue {
	name: string | null;
	ivalue: number | null;
	fvalue: number | null;
	svalue: Uint8Array | null;
}
export interface DataCenterPing {
	data_center_id: number | null;
	ping: number | null;
}
export interface GlobalStatistics {
	players_online: number | null;
	servers_online: number | null;
	players_searching: number | null;
	servers_available: number | null;
	ongoing_matches: number | null;
	search_time_avg: number | null;
	search_statistics: DetailedSearchStatistic[];
	main_post_url: string | null;
	required_appid_version: number | null;
	pricesheet_version: number | null;
	twitch_streams_version: number | null;
	active_tournament_eventid: number | null;
	active_survey_id: number | null;
	rtime32_cur: number | null;
	required_appid_version2: number | null;
}
export interface DetailedSearchStatistic {
	game_type: number | null;
	search_time_avg: number | null;
	players_searching: number | null;
}
export interface PlayerCommendationInfo {
	cmd_friendly: number | null;
	cmd_teaching: number | null;
	cmd_leader: number | null;
}
export interface PlayerMedalsInfo {
	display_items_defidx: number[];
	featured_display_item_defidx: number | null;
}
export interface AccountActivity {
	activity: number | null;
	mode: number | null;
	map: number | null;
	matchid: string | null;
}
export interface CMsgGCCStrike15_v2_MatchList {
	msgrequestid: number | null;
	accountid: number | null;
	servertime: number | null;
	matches: CDataGCCStrike15_v2_MatchInfo[];
	streams: TournamentTeam[];
	tournamentinfo: CDataGCCStrike15_v2_TournamentInfo | null;
}
export interface CDataGCCStrike15_v2_MatchInfo {
	matchid: string | null;
	matchtime: number | null;
	watchablematchinfo: WatchableMatchInfo | null;
	roundstats_legacy: CMsgGCCStrike15_v2_MatchmakingServerRoundStats | null;
	roundstatsall: CMsgGCCStrike15_v2_MatchmakingServerRoundStats[];
}
export interface WatchableMatchInfo {
	server_ip: number | null;
	tv_port: number | null;
	tv_spectators: number | null;
	tv_time: number | null;
	tv_watch_password: Uint8Array | null;
	cl_decryptdata_key: string | null;
	cl_decryptdata_key_pub: string | null;
	game_type: number | null;
	game_mapgroup: string | null;
	game_map: string | null;
	server_id: string | null;
	match_id: string | null;
	reservation_id: string | null;
}
export interface CMsgGCCStrike15_v2_MatchmakingServerRoundStats {
	reservationid: string | null;
	reservation: CMsgGCCStrike15_v2_MatchmakingGC2ServerReserve | null;
	map: string | null;
	round: number | null;
	kills: number[];
	assists: number[];
	deaths: number[];
	scores: number[];
	pings: number[];
	round_result: number | null;
	match_result: number | null;
	team_scores: number[];
	confirm: CMsgGCCStrike15_v2_MatchmakingGC2ServerConfirm | null;
	reservation_stage: number | null;
	match_duration: number | null;
	enemy_kills: number[];
	enemy_headshots: number[];
	enemy_3ks: number[];
	enemy_4ks: number[];
	enemy_5ks: number[];
	mvps: number[];
	spectators_count: number | null;
	spectators_count_tv: number | null;
	spectators_count_lnk: number | null;
	enemy_kills_agg: number[];
	drop_info: CMsgGCCStrike15_v2_MatchmakingServerRoundStats_DropInfo | null;
	b_switched_teams: boolean | null;
	enemy_2ks: number[];
	player_spawned: number[];
	team_spawn_count: number[];
	max_rounds: number | null;
	map_id: number | null;
}
export interface CMsgGCCStrike15_v2_MatchmakingGC2ServerConfirm {
	token: number | null;
	stamp: number | null;
	exchange: string | null;
	retry: number | null;
}
export interface CMsgGCCStrike15_v2_MatchmakingServerRoundStats_DropInfo {
	account_mvp: number | null;
}
export interface CDataGCCStrike15_v2_TournamentInfo {
	sections: CDataGCCStrike15_v2_TournamentSection[];
	tournament_event: TournamentEvent | null;
	tournament_teams: TournamentTeam[];
}
export interface CDataGCCStrike15_v2_TournamentSection {
	sectionid: number | null;
	name: string | null;
	desc: string | null;
	groups: CDataGCCStrike15_v2_TournamentGroup[];
}
export interface CDataGCCStrike15_v2_TournamentGroup {
	groupid: number | null;
	name: string | null;
	desc: string | null;
	picks__deprecated: number | null;
	teams: CDataGCCStrike15_v2_TournamentGroupTeam[];
	stage_ids: number[];
	picklockuntiltime: number | null;
	pickableteams: number | null;
	points_per_pick: number | null;
	picks: CDataGCCStrike15_v2_TournamentGroup_Picks[];
}
export interface CDataGCCStrike15_v2_TournamentGroupTeam {
	team_id: number | null;
	score: number | null;
	correctpick: boolean | null;
}
export interface CDataGCCStrike15_v2_TournamentGroup_Picks {
	pickids: number[];
}
export interface CMsgGCCStrike15_v2_GC2ClientNotifyXPShop {
	prematch: CSOAccountXpShop | null;
	postmatch: CSOAccountXpShop | null;
	current_xp: number | null;
	current_level: number | null;
}
export interface CSOAccountXpShop {
	generation_time: number | null;
	redeemable_balance: number | null;
	xp_tracks: number[];
}
export interface CMsgRecurringMissionSchema {
	missions: CMsgRecurringMissionSchema_MissionTemplateList[];
}
export interface CMsgRecurringMissionSchema_MissionTemplateList {
	period: number | null;
	mission_templates: Uint8Array[];
}
export interface CMsgGCCStrike15_v2_PremierSeasonSummary {
	account_id: number | null;
	season_id: number | null;
	data_per_week: CMsgGCCStrike15_v2_PremierSeasonSummary_DataPerWeek[];
	data_per_map: CMsgGCCStrike15_v2_PremierSeasonSummary_DataPerMap[];
}
export interface CMsgGCCStrike15_v2_PremierSeasonSummary_DataPerWeek {
	week_id: string | null;
	rank_id: number | null;
	matches_played: number | null;
}
export interface CMsgGCCStrike15_v2_PremierSeasonSummary_DataPerMap {
	map_id: number | null;
	wins: number | null;
	ties: number | null;
	losses: number | null;
	rounds: number | null;
	kills: number | null;
	headshots: number | null;
	assists: number | null;
	deaths: number | null;
	mvps: number | null;
	rounds_3k: number | null;
	rounds_4k: number | null;
	rounds_5k: number | null;
}
export interface CMsgGCCStrike15_v2_MatchmakingGC2ClientSearchStats {
	gs_location_id: number | null;
	data_center_id: number | null;
	num_locked_in: number | null;
	num_found_nearby: number | null;
	note_level: number | null;
}
